### ISSUE TITLE
Minimum version of Java 8 or 11

### ISSUE THREAD

**Issue by daniel-augusto** [fabriciorby/maven-surefire-junit5-tree-reporter#14]
In pom.xml we see references to Java 8: https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/blob/master/pom.xml#L18

```
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
```

But in github workflow, we see a reference to Java 11: https://github.com/fabriciorby/maven-surefire-junit5-tree-reporter/blob/master/.github/workflows/maven-publish.yml#L16

```
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
```
I suggest aligning these versions.
